apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: pyui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: yafit12/pyui:v1
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: host
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: S3_BUCKET
          value: "yafit-s3-bucket"
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"