name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kubernetes
        run: |
          kubectl apply -f k8scd_local/k8s-manifests/deployment.yaml
          kubectl apply -f k8scd_local/k8s-manifests/service.yaml
          kubectl apply -f k8scd_local/k8s-manifests/statefulset-mysql.yaml
          kubectl apply -f k8scd_local/k8s-manifests/configmap.yaml
          kubectl apply -f k8scd_local/k8s-manifests/secret.yaml
